### ISSUE TITLE
Missing Icon for AssetThumbnailWidget_16x.png

### ISSUE THREAD

**Issue by Ryan-DowlingSoka** [mhousse1247/UE4-EditorScriptingToolsPlugin#10]
https://github.com/mhousse1247/UE4-EditorScriptingToolsPlugin/blob/c40c768e1c4b75f59d531551b31d580b0936b5cd/Plugins/EditorScriptingTools/Source/EditorScriptingTools/Private/EditorScriptingToolsStyle.cpp#L139

Hi!

We've hit a warning on the referenced icon that seems to be missing.
"Resources/Icons/AssetThumbnailWidget_16x.png"

Isn't in the project, but is referenced in EditorScriptingToolsStyle.cpp#L139

My guess is this icon just got missed from being added, but if we need to remove the style like that works too.

**Comment by mhousse1247** [comment]
Hello!

I simply removed the style for now , I will try to find a suitable icon for the next update.

Btw, the next update ( v1.0 ) is coming soon :) I've deprecated a lot of stuff , but I think there will some manual work to fix some broken stuff :p .
This repo will host plugin source only , and I will publish an other repo containing example projects :)

**Comment by Ryan-DowlingSoka** [comment]
That would be great. :)

As far as changes, thanks for the heads up. Hopefully it won't be too bad. I'm excited for the new features.
