### ISSUE TITLE
[Suggestion] Make this plugin more convenient to be used in other project

### ISSUE THREAD

**Issue by ameaninglessname** [mhousse1247/UE4-EditorScriptingToolsPlugin#11]
Because it is a project right now, we can't simply clone it to our project's plugins folder.

Maybe you could create a new reposition which contains only the **EditorScriptingTools** plugin, and let this repo refer it as a submodule.

Or turn this project into a plugin, move the content to plugin content, and so on.

These are just my humble opinion. And this plugin is great, thanks a lot.

**Comment by mhousse1247** [comment]
Yeah, I've already planned that ( Talked about it yesterday here :)
https://github.com/mhousse1247/UE4-EditorScriptingToolsPlugin/issues/10#issuecomment-864120476 )

But thanks for the suggestion anyway , and glad you find the plugin useful.
