### ISSUE TITLE
Does not build with No-Unity or No-PCH

### ISSUE THREAD

**Issue by Ryan-DowlingSoka** [mhousse1247/UE4-EditorScriptingToolsPlugin#2]
This plugin runs great when AdaptiveUnity and PCH files are built, but fails non-unity non-pch builds quite dramatically. Lots of missing includes across .h and .cpp files.

Adding these lines to the EditorScriptingTools.Build.cs can help discover these issues:

```cs        
    //PCHUsage = ModuleRules.PCHUsageMode.UseExplicitOrSharedPCHs;
    PCHUsage = ModuleRules.PCHUsageMode.NoPCHs;
    bUseUnity = false;
```

**Comment by mhousse1247** [comment]
Yeah I , forgot to check the dependencies  in non-unity mode.
But I will fix this issue in the next update soon :)
