### ISSUE TITLE
Question: Ability to create a dedicated editor mode for a specific blueprint class?

### ISSUE THREAD

**Issue by Ryan-DowlingSoka** [mhousse1247/UE4-EditorScriptingToolsPlugin#3]
Hi! I've been really really impressed with this plugin, and it has helped me make a very complicated editor mode in a fraction of the time it would've taken in slate.

Thanks very much!

A question I have, is if you believe it is possible (and where should I start) if I wanted to create an editor module that started a particular edmode tool's blueprint.

I can see some places I could hack it into the existing setup, but I'd prefer to create a new edmode in C++ and then spawn the widget. I can probably figure my way around it, but if you have any insight or places to start looking, I'd appreciate it.

**Comment by Ryan-DowlingSoka** [comment]
After digging a bit into this, I think I have the basic idea of what I would like to do, but have run up against some blockers.

I was thinking that I could create a subclass of the BluEdMode that loaded a particular blueprint on Initialize. The big issue with this plan is that the vast majority of the header files in the plugin are in the private folder, and currently aren't exposed with the EDITORSCRIPTINGTOOLS_API so I would have to have my editor mode defined in your plugin stead of external as is.

After some hackery and surgery to bring most of the headers to public and add the EDITORSCRIPTINGTOOLS_API to FBluEdMode and UEditorModeToolUtilityBlueprint I did get this to work, but now my version is really disparate from your source. Something we are definitely trying to avoid on our team is getting far from the source for the plugins and engine source we use.

But after those changes anyway I'd be able to run the Initialize similar to this:

```cpp
void FMyEdMode::Initialize()
{
	SetCurrentToolBlueprint(LoadObject<UEditorModeToolUtilityBlueprint>(nullptr, TEXT("/FMyPlugin/Editor/BP_EditorMode.BP_EditorMode")), true);
}

void FMyEdMode::Enter()
{
	Super::Enter();
	ReloadTool();
}
```

Which is working for me. Perhaps I should re-open this an issue saying that BluEdMode and EditorModeToolUtilityBlueprints aren't accessible outside of the EditorScriptingTools plugin? What are your thoughts?

**Comment by mhousse1247** [comment]
Hi!

Is there any specific need to create an editor mode to runs your ModeTools blueprints ?

Because you can use these nodes with an EditorUtilityWidget to manage your tools

![EditorModeToolNodes](https://user-images.githubusercontent.com/7004281/111025525-fae49a80-83e4-11eb-9ad1-ac48e8871a72.png)

**Comment by Ryan-DowlingSoka** [comment]
The need is only just for artist convenience. We aren't likely going to have several of these, but if we register our own full edmode then it gets added with the shortcut so (Shift+#) works, and it feels more like a native edmode.

We could go down the path you describe, but it would then be a different flow from the other edmodes. My hope is to use your tool to avoid the need to write lots of slate code more than it is to avoid writing any C++.  Is there a particular design reason you are avoiding making these things classes exposed to other modules? Just API maintenance for future versions?

**Comment by mhousse1247** [comment]
For now I'd like to keep plugin classes private , so extensions could be done only from data/blueprint side.
Also , with the actual design of BluEdmode, making it classes public is not enough even if it seems to works,  some other code changes need to be done.

I've already started a solution , that will register single modes for registered ModeToolBlueprints ( via editor settings)

**Comment by Ryan-DowlingSoka** [comment]
Sounds good. Making the classes private and adding the MODULE_API is basically all it takes to do the ed mode (only know because I've done it), but I understand your reticence to go down that path. I'll revert to yours and wait for the registration single mode solution from you, Thanks!

**Comment by mhousse1247** [comment]
Hi!
Now you can register a custom Ed Mode per ModeToolUtilityBlueprint :)
Also there is a settings tab ( still WIP ) Window -> Editor Scripting Tool -> Editor Scripting Tools Settings

![BluEdModes](https://user-images.githubusercontent.com/7004281/113875241-d77bf800-97b6-11eb-8671-c3ff3032ed50.png)
