### ISSUE TITLE
Register OnExecuteUserDefinedAction on tool start and end.

### ISSUE THREAD

**Issue by Ryan-DowlingSoka** [mhousse1247/UE4-EditorScriptingToolsPlugin#4]
Hi!

I was trying to use UserDefinedActions as a way to do particular user events in an Editor Mode Tool. I found that the Event On Execute User Defined Action was not bound to.

![image](https://user-images.githubusercontent.com/3629598/111231354-5a3dd880-85a6-11eb-8f87-69a76eb97175.png)

I found that if on ReloadTool and UnloadTool I could register the OnExecuteUserDefinedAction to get around this, but then was wondering if I was just using these used defined actions wrong. Perhaps I should just be checking for particular inputs in the editor mode instead? I could do that in the receive tick and check the currently down keys, but that felt wrong to me: but I realized I might be missing something more obvious.

BluEdMode.cpp::ReloadTool()
```cpp
				ToolBlueprint->OnRegisterDone();

				if (GEditor)
				{
					GEditor->OnBlueprintReinstanced().AddSP(this, &FBluEdMode::HandleAnyBlueprintReinstanced);

					//Addition: Bind to execute user defined action.
					UEditorEventsSubsystem* EditorEventsSubsystem = GEditor->GetEditorSubsystem<UEditorEventsSubsystem>();
					if (EditorEventsSubsystem)
					{
						EditorEventsSubsystem->OnExecuteUserDefinedAction.AddDynamic(ActiveToolWeakPtr.Get(false), &UEditorModeToolInstance::OnExecuteUserDefinedAction);
					}
				}
```

```cpp
void FBluEdMode::UnloadTool(bool bRefreshSlateWidget /*= true*/)
{
	if (GEditor)
	{
		GEditor->OnBlueprintReinstanced().RemoveAll(this);

		//Addition: Unbind to execute user defined action.
		UEditorEventsSubsystem* EditorEventsSubsystem = GEditor->GetEditorSubsystem<UEditorEventsSubsystem>();
		if (EditorEventsSubsystem)
		{
			if (ActiveToolWeakPtr.IsValid(true))
			{
				EditorEventsSubsystem->OnExecuteUserDefinedAction.RemoveAll(ActiveToolWeakPtr.Get(true));
			}
		}
	}
```

(Again, I can't say how much I am absurdly impressed with this plugin. Really fantastic. 👍 👍 👍 )

**Comment by mhousse1247** [comment]
You need to map(register) your UserDefinedActions before. For example : 

![UserDefinedActions](https://user-images.githubusercontent.com/7004281/111334205-a571ed00-8673-11eb-8e0c-1247a921b308.png)

But one thing to keep in mind , you can not block other editor registered actions , for example if you use "Delete" key in your tool , the editor default delete action will be executed too.

I've made UserDefinedActions essentially for tools like UtilityWidgets , to be able to use input with these kind of tool when Level Editor has focus.

For EditorModeTools , it's better to override HandleInputKey event ( return true mean the priority if for this tool and will not execute other editor tools and actions )

![HandleInputKey](https://user-images.githubusercontent.com/7004281/111335007-52e50080-8674-11eb-996f-79d10a6e3dc6.png)

**Comment by Ryan-DowlingSoka** [comment]
Thanks! That makes sense.
