### ISSUE TITLE
Editor User Defined Settings - Edit to saved local configs instead of default.

### ISSUE THREAD

**Issue by Ryan-DowlingSoka** [mhousse1247/UE4-EditorScriptingToolsPlugin#5]
Hi! Another thing I was looking to learn how to do is save some user configuration of the edit-tool per user. This may not be what the EditorUserDefinedSettings are for.

Making 
![image](https://user-images.githubusercontent.com/3629598/111498332-18747580-86ff-11eb-9700-8610d08c45aa.png) 
this change lets me change the user saved, but I'm not sure how I would guarantee that this is registered.

I think in my particular case I think I might put my config stuff in code, since that is relatively easy to do, but was wondering if you had thoughts on how to save editor mode like configuration settings per user.

( As example: I have a tool that has 2 sub-modes, I want to save which mode the user used last since in my tool most users will only ever use one of the two modes. )

**Comment by mhousse1247** [comment]
Hey!

Maybe "config = EditorPerProjectUserSettings" is what you are looking for

**Comment by Ryan-DowlingSoka** [comment]
Okay, sounds like the recommendation is to just change the code here then.
Thanks!
