### ISSUE TITLE
Editor Mode : On Level Save Override

### ISSUE THREAD

**Issue by Ryan-DowlingSoka** [mhousse1247/UE4-EditorScriptingToolsPlugin#7]
Would it be possible to consume and handle an On Level Save call?
In the tool I am creating a lot of work while in the editor mode is in a 'live' state. When the editor mode closes, currently, I bake all of the live information into static information. The problem then is if someone saves before closing the editor mode, the data is still in the live state, and isn't actually cached.

I was looking to see if there was an On Level Save hook I could handle in the Editor Mode, to catch that, and force a bake to the static mode, or forcibly close the editormode.

**Comment by mhousse1247** [comment]
I've added 2 events to "EditorEventsSubsystem", so if you can like to catch thing before or after save

![WorldSave](https://user-images.githubusercontent.com/7004281/113719234-af749200-96ed-11eb-9ee0-c2cad39b1914.png)

**Comment by Ryan-DowlingSoka** [comment]
Perfect!
